ALTER TABLE PTBL_CATEGORY
ADD CONSTRAINT UNQ_CATEGORY_NAME
    UNIQUE (CATEGORY_NAME);
    
    
ALTER TABLE PTBL_TRANSACTION
MODIFY (QUANTITY NUMBER(4,0) DEFAULT 1);

ALTER TABLE PTBL_CATEGORY
ADD CONSTRAINT CHK_CATEGORY_PRODUCT_CATEGORY_ID
    CHECK (PRODUCT_CATEGORY_ID >= 0);
    
ALTER TABLE PTBL_SUBCATEGORY
ADD CONSTRAINT PK_TBL_SUBCATEGORY
    PRIMARY KEY (PRODUCT_SUBCATEGORY_ID);
    
    
ALTER TABLE PTBL_PRODUCT
ADD CONSTRAINT PK_PTBL_PRODUCT_PRODUCT_SUBCATEGORY_ID
    FOREIGN KEY (PRODUCT_SUBCATEGORY_ID)
    REFERENCES PTBL_SUBCATEGORY(PRODUCT_SUBCATEGORY_ID)
    ENABLE NOVALIDATE;