SELECT CATEGORY_NAME, SUBCATEGORY_NAME
    , COUNT(PRODUCT_ID) AS NUMBER_OF_PRODUCTS
FROM ptbl_product 
NATURAL FULL OUTER JOIN ptbl_subcategory 
NATURAL FULL OUTER JOIN ptbl_category 
GROUP BY CATEGORY_NAME, SUBCATEGORY_NAME
ORDER BY CATEGORY_NAME, SUBCATEGORY_NAME;