SELECT  SUBCATEGORY_NAME, TRANSACTION_DATE
    , SUM(ACTUAL_COST) AS TOTAL_ACTUAL_COST
    , SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ptbl_transaction T
NATURAL FULL OUTER JOIN ptbl_product 

NATURAL FULL OUTER JOIN ptbl_subcategory 

GROUP BY SUBCATEGORY_NAME, TRANSACTION_DATE
ORDER BY SUBCATEGORY_NAME, TRANSACTION_DATE;    